robot: "g1"  # Robot name, "go2", "b2", "b2w", "h1", "go2w", "g1"
robot_scene: "scene_29dof.xml" # Robot scene, /unitree_robots/[robot]/scene.xml 

domain_id: 0  # Domain id  g1 0  go2 1
interface: "lo" # Interface "lo" 表示使用本地回环接口（localhost），适合仿真环境。

use_joystick: 1 # 启用游戏手柄模拟 Unitree 的无线控制器
joystick_type: "xbox" # support "xbox" and "switch" gamepad layout
joystick_device: "/dev/input/js0" # Device path
joystick_bits: 16 # Some game controllers may only have 8-bit accuracy

print_scene_information: 1 # Print link, joint and sensors information of robot

enable_elastic_band: 1 # Virtual spring band, used for lifting h1 模拟 H1 机器人初始化时的悬挂过程
